### ISSUE TITLE
Gradio doesn't appear in directory

### ISSUE THREAD

**Issue by DrMemoryFish** [smitec/whisper-gradio#1]
I cd'd into the directory I wanted to install Gradio to (E:\AI), however, when I went into E:\AI it wasn't there.

https://imgur.com/a/8gWPWe4

I thought maybe that's how it's supposed to be, so I entered:

`run.py`

and got this in return:

```
(base) E:\AI>run.py
'run.py' is not recognized as an internal or external command,
operable program or batch file.

(base) E:\AI>
```

what am I doing wrong?

**Comment by DrMemoryFish** [comment]
I got this error:
```
(base) C:\Users\Abdullah>gradio
Traceback (most recent call last):
  File "C:\Users\Abdullah\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Abdullah\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Abdullah\miniconda3\Scripts\gradio.exe\__main__.py", line 4, in <module>
  File "C:\Users\Abdullah\miniconda3\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\Abdullah\miniconda3\lib\site-packages\gradio\components.py", line 31, in <module>
    import matplotlib.figure
  File "C:\Users\Abdullah\miniconda3\lib\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "C:\Users\Abdullah\miniconda3\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\Abdullah\miniconda3\lib\site-packages\matplotlib\colors.py", line 51, in <module>
    from PIL import Image
ImportError: cannot import name 'Image' from 'PIL' (unknown location)

(base) C:\Users\Abdullah>
```

what does this mean?

**Comment by smitec** [comment]
Hey @AbdullahJames couple of questions, will do my best to help.

Is `AI` the folder which has the code from this repo in it?

you'll also need to run `pip install gradio` before running run.py

lastly there are some instructions on the whisper repo you'll need to follow (https://github.com/openai/whisper#setup)

Can you let me know if you've run all those and that should help us narrow down the source of the error. I wasn't able to see much detail in the attached screenshot.
